---
Title: Técnicas de limpeza e tratamento de dados
Author: Álvaro Robério de Souza Sá
---

# Importando a Base de Dados

```{r}

# Importando dados, string vazio como NA, string como fatores

dados <- read.csv("Churn.csv", sep= ";", na.strings="", stringsAsFactors = T)
head(dados)
summary(dados)

```

# Renomeando Colunas 

```{r}

# Nomeando as colunas corretamente 

colnames(dados) = c( "Id", "Score", "Estado", "Genero", 
                     "idade", "Patrimonio", "Saldo", "Produtos",
                     " TemCartCredito", "Ativo", "Salario", 
                     "Saiu")
head(dados)

```

# Explorando os Dados 

```{r}

#Estados - Contagem e Gráfico de Barras 

counts <- table(dados$Estado)
barplot(counts, main="Estados", xlab="Estados")

# Gêneros - Contagem e Gráfico de Barras 

counts <- table(dados$Genero)
barplot(counts, main="Gêneros", xlab="Gêneros")

```

# Explorando Colunas Númericas

```{r}

#Score 

summary(dados$Score)
boxplot(dados$Score)
hist(dados$Score)

#Idade 

summary(dados$idade)
boxplot(dados$idade)
hist(dados$idade)

#Saldo 

summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)

#Salário  

summary(dados$Salario)
boxplot(dados$Salario)
hist(dados$Salario)

```

# Tratamento - Valores Faltantates (NAs)

```{r}

# Tratanto valores ausentes (! = sinal de negação)

dados[!complete.cases(dados),]

```

# Tratamento de Salários - Dado Númerico 

```{r}
# Tratar salários
summary(dados$Salario)

# Ver mediana 

median(dados$Salario, na.rm=T)

# Atribuir Mediana nos NAS

dados[is.na(dados$Salario), ]$Salario = median(dados$Salario, na.rm = T)

# Buscar Nas em salario para checar 

dados[!complete.cases(dados$Salario),]

```

# Falta de Padronização em Gênero - Dado Categorico 

```{r}

# Ver Valores 

unique(dados$Genero)
summary(dados$Genero)

# Transformação F e Fem em Femino 
# Transformação M em Masulino 

dados[is.na(dados$Genero) | dados$Genero == "M",]$Genero = "Masculino"
dados[dados$Genero == "F" | dados$Genero == "Fem",]$Genero = "Feminino"

# Ver resultado
summary(dados$Genero)

# Remover levels não utilizados 

dados$Genero = factor(dados$Genero)

# Visualizar novamente
summary(dados$Genero)

```

# Idades fora do domínio 

```{r}

summary(dados$idade)

# fora do domínio, numérico - ver idades anormais 

dados[dados$idade<0 | dados$idade>110 ,]$idade

# não temos idade NAs

dados[is.na(dados$idade)]

# opção, preencher com mediana

median(dados$idade)

# Substituição 

dados[dados$idade<0 | dados$idade>110 ,]$idade = median(dados$idade)

# Buscamos novamente idade anormais

dados[dados$idade<0 | dados$idade>110 ,]

summary(dados$idade)

```

# Dados duplicados 

```{r}
# Buscar duplicados pelo ID 

x <-  dados[duplicated(dados$Id), ]
x

# Verificamos que o ID 81 está duplicado 
# Vamos excluir pelo ID e não pelo índice 

dados <- dados[!dados$Id %in% c(x$Id), ]

# Buscamos a linha que estava duplicada 

dados[dados$Id == x$Id, ]

# Verificamos novamente duplicados 

x <-  dados[duplicated(dados$Id), ]
x

```

# Estado forma do domínio

```{r}

# Fora do domínio - Categórico 

unique(dados$Estado)
summary(dados$Estado)

# Preencher com a moda, RS 

dados[!dados$Estado %in% c("RS", "SC", "PR"), ]$Estado = "RS"
summary(dados$Estado)

# Removendo fatores não usados 

dados$Estado = factor(dados$Estado)

# Visualizar novamente

summary(dados$Estado)

```

# Identificando Outliers 

```{r}

# Outliers, criando um parâmetro com desvio padrão 

desv <- sd(dados$Salario, na.rm=T)
desv
dados[dados$Salario >= 2*desv, ]$Salario

# Outra forma, resultado semelhante, mas sem os NAs

boxplot(dados$Salario)
boxplot(dados$Salario, outline = F)

x = boxplot(dados$Salario)$out
x

# Atualizando todos para mediana 

median(dados$Salario)
dados[dados$Salario >= 2*desv, ]$Salario = median(dados$Salario)

# Checando se sairam os outliers 

dados[dados$Salario >= 2*desv, ]$Salario

```

